### PR TITLE
Remove vendoring

### PR DESCRIPTION
**Pull request by sagikazarmark**
Requires #60 to be merged first

### CODE REVIEW

**Review by natoscott — APPROVED** [review]
LGTM.

**Comment by sagikazarmark** [comment]
@natoscott fixed!

Do you think you could tag a new version after merging this one? That would be great!

**Comment by natoscott** [comment]
> @natoscott fixed!

Thanks!

> Do you think you could tag a new version after merging this one? That would be great!

Sure, will look into it.

**Comment by natoscott** [comment]
> > Do you think you could tag a new version after merging this one? That would be great!
> 
> Sure, will look into it.

@sagikazarmark OK, done - I've tagged a 3.1.0 and given the repo a fresh coat of paint in terms of:

- updated README, using pointers to modern PCP, Grafana and Vector docs
- renamed 'master' branch to 'main'
- added link to PCP sponsorship page
- updated the CHANGELOG and version in speed.so

Let me know if you see anything amiss please?  Thanks!

**Pull request merged**
